# [DL4006](https://github.com/hadolint/hadolint/wiki/DL4006): Set the SHELL option -o pipefail before RUN with a pipe in

このエラーは、RUNコマンドでパイプを使う際のエラーである。

`a | b`というコマンドは、`a`が失敗してもその失敗結果を`b`へ繋げる。  
最終的にこのコマンドの終了ステータスは`b`の結果に左右される。  
つまるところ、`a`が失敗して`b`が成功した場合、成功の終了ステータスが得られる。  

具体的には

```dockerfile
RUN wget -O - https://some.site | wc -l > /number
```

`wget`に失敗しても`wc`が成功していれば、このRUNは成功を返してイメージの構築を継続する。  
これは期待した動作ではないので、以下のスクリプトを入れる。

```dockerfile
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN wget -O - https://some.site | wc -l > /number
```

`pipefail`は、パイプ前後で失敗した場合にその場でエラーを返すオプションである。  
これにより、`wget`に失敗したらそこでイメージの構築に失敗させることができる。
